/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_ESNIERR_H
# define HEADER_ESNIERR_H

# include <openssl/opensslconf.h>
# include <openssl/symhacks.h>


# ifdef  __cplusplus
extern "C"
# endif
int ERR_load_ESNI_strings(void);

/*
 * ESNI function codes.
 */
# if !OPENSSL_API_3
#  define ESNI_F_BASE64_DECODE                             0
#  define ESNI_F_CHECKSUM_CHECK                            0
#  define ESNI_F_DEC                                       0
#  define ESNI_F_ENC                                       0
#  define ESNI_F_ESNI_AEAD_DEC                             0
#  define ESNI_F_ESNI_AEAD_ENC                             0
#  define ESNI_F_ESNI_BASE64_DECODE                        0
#  define ESNI_F_ESNI_CHECKSUM_CHECK                       0
#  define ESNI_F_ESNI_MAKE_RD                              0
#  define ESNI_F_ESNI_MAKE_SE_FROM_ER                      0
#  define ESNI_F_ESNI_KEY_DERIVATION                       0
#  define ESNI_F_MAKEESNICONTENTHASH                       0
#  define ESNI_F_NEW_FROM_BASE64                           0
#  define ESNI_F_SERVER_ENABLE                             0
#  define ESNI_F_SSL_ESNI_DEC                              0
#  define ESNI_F_SSL_ESNI_DUP                              0
#  define ESNI_F_SSL_ESNI_ENC                              0
#  define ESNI_F_SSL_ESNI_GREASE_ME                        0
#  define ESNI_F_SSL_ESNI_NEW_FROM_BASE64                  0
#  define ESNI_F_SSL_ESNI_NEW_FROM_BUFFER                  0
#  define ESNI_F_SSL_ESNI_QUERY                            0
#  define ESNI_F_SSL_ESNI_RECORD_NEW_FROM_BINARY           0
#  define ESNI_F_SSL_ESNI_REDUCE                           0
#  define ESNI_F_SSL_ESNI_SERVER_ENABLE                    0
#  define ESNI_F_SSL_ESNI_WRAP_KEYSHARE                    0
# endif

/*
 * ESNI reason codes.
 */
# define ESNI_R_ASCIIHEX_DECODE_ERROR                     113
# define ESNI_R_BAD_INPUT                                 114
# define ESNI_R_BASE64_DECODE_ERROR                       110
# define ESNI_R_NOT_IMPL                                  112
# define ESNI_R_RR_DECODE_ERROR                           111

#endif
